//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDotNet.Models.tesDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int id_category { get; set; }
        public string location { get; set; }
        public decimal salary { get; set; }
        public System.DateTime date_posted { get; set; }
        public bool is_active { get; set; }
        public int id_recruiter { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Category Category { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
