//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDotnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id { get; set; }
        public int job_id { get; set; }
        public int candidate_id { get; set; }
        public string cover_letter { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
